from __future__ import annotations

from math import ceil

PIX_PER_METER = 100
AGENT_RADIUS = 1.5
MAX_AGENT_RADIUS = ceil(AGENT_RADIUS) * PIX_PER_METER // 10
MIN_AGENT_RADIUS = round(AGENT_RADIUS) * PIX_PER_METER // 10
AGENT_DIAMETER = MAX_AGENT_RADIUS + MIN_AGENT_RADIUS

OBSTACLE_SPACE = 0
FREE_SPACE = 1
RADIUS_METERS = 0.125
RADIUS_PIXELS = round(RADIUS_METERS * PIX_PER_METER)

__all__ = [
    "PIX_PER_METER",
    "AGENT_RADIUS",
    "MAX_AGENT_RADIUS",
    "MIN_AGENT_RADIUS",
    "AGENT_DIAMETER",
    "OBSTACLE_SPACE",
    "FREE_SPACE",
    "RADIUS_METERS",
    "RADIUS_PIXELS",
]
