"""Utility functions and helpers for NavIRL."""

from __future__ import annotations

from navirl.utils.geometry import (
    angle_between,
    angle_diff,
    angular_velocity,
    circle_circle_intersection,
    closest_point_on_line,
    cross2d,
    distance,
    dot2d,
    heading_from_velocity,
    line_segment_intersection,
    normalize_angle,
    normalize_vector,
    point_in_polygon,
    point_to_line_distance,
    polygon_area,
    rotate_point,
    wrap_angle,
)
from navirl.utils.math_utils import (
    clamp,
    exponential_moving_average,
    gaussian_kernel,
    lerp,
    running_mean,
    running_std,
    sigmoid,
    softmax,
)
from navirl.utils.spatial import (
    KDTree2D,
    SpatialHashGrid,
    find_k_nearest,
    find_neighbors_in_radius,
)
from navirl.utils.timing import Timer, profile, rate_limiter, throttle

__all__ = [
    "angle_between",
    "angle_diff",
    "angular_velocity",
    "circle_circle_intersection",
    "clamp",
    "closest_point_on_line",
    "cross2d",
    "distance",
    "dot2d",
    "exponential_moving_average",
    "find_k_nearest",
    "find_neighbors_in_radius",
    "gaussian_kernel",
    "heading_from_velocity",
    "KDTree2D",
    "lerp",
    "line_segment_intersection",
    "normalize_angle",
    "normalize_vector",
    "point_in_polygon",
    "point_to_line_distance",
    "polygon_area",
    "profile",
    "rate_limiter",
    "rotate_point",
    "running_mean",
    "running_std",
    "sigmoid",
    "softmax",
    "SpatialHashGrid",
    "throttle",
    "Timer",
    "wrap_angle",
]
