from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

AgentKind = Literal["robot", "human"]


@dataclass(slots=True)
class AgentState:
    """
    Complete state information for one agent at a single simulation timestep.

    This class encapsulates all the information needed to describe an agent's
    current status, including position, velocity, goals, and physical constraints.
    Used extensively throughout the simulation for collision avoidance, path planning,
    and behavior generation.

    Attributes:
        agent_id: Unique identifier for this agent
        kind: Type of agent ("robot" or "human")
        x: Current x-coordinate position in meters
        y: Current y-coordinate position in meters
        vx: Current velocity in x-direction (m/s)
        vy: Current velocity in y-direction (m/s)
        goal_x: Target x-coordinate position in meters
        goal_y: Target y-coordinate position in meters
        radius: Physical radius of the agent for collision detection (meters)
        max_speed: Maximum allowed speed for this agent (m/s)
        behavior: Current behavior mode (e.g., "GO_TO", "STOP", "FOLLOW")
        metadata: Additional context-specific data for debugging/analysis
    """

    agent_id: int
    kind: AgentKind
    x: float
    y: float
    vx: float
    vy: float
    goal_x: float
    goal_y: float
    radius: float
    max_speed: float
    behavior: str = "GO_TO"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class Action:
    """
    Action command generated by a controller for one simulation timestep.

    Controllers generate Action objects to specify how an agent should behave
    during the next timestep. The action includes preferred velocity and
    behavior mode for collision avoidance algorithms.

    Attributes:
        pref_vx: Preferred velocity in x-direction (m/s)
        pref_vy: Preferred velocity in y-direction (m/s)
        behavior: Behavior mode ("GO_TO", "STOP", "FOLLOW", etc.)
        metadata: Additional context data for debugging/analysis
    """

    pref_vx: float
    pref_vy: float
    behavior: str = "GO_TO"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class EventRecord:
    """Discrete event emitted during simulation."""

    step: int
    time_s: float
    event_type: str
    agent_id: int | None
    payload: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class Observation:
    """Per-step observation passed to controllers."""

    step: int
    time_s: float
    agents: dict[int, AgentState]


@dataclass(slots=True)
class EpisodeLog:
    """Pointers to run artifacts."""

    run_id: str
    bundle_dir: str
    scenario_path: str
    state_path: str
    events_path: str
    summary_path: str
